name: spiketutorial
dependencies:
  - python=3.8
  - pip
  - pyqt
  - cython
  - pillow
  - pip:
    - numpy
    - h5py
    - cython
    - tqdm
    - click
    - pillow
    - scipy
    - matplotlib
    - seaborn
    - scikit-learn
    - klusta
    - klustakwik2
    - jupyter
    - pynwb
    - pyopenephys
    - probeinterface
    - spikeinterface==0.12.0
    - phy==2.0b1
