name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=22.0
  - numpy
  - joblib
  - tqdm
  - pillow
  - sphinx-gallery
  - numpydoc
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  - networkx
  - pybind11
  - loky
  - hdbscan
  - numba
  - jupyter
  - pyqt=5
  - pyqtgraph
  - pip:
    - neo
    - spikeinterface[full,widgets]>=0.98
    - probeinterface
    - spikeinterface-gui
    - tridesclous
    # - phy==2.0b5
    - docker
